### ISSUE TITLE
Deep transformation does not work

### ISSUE THREAD

**Issue by kuksik** [prisma/binding-argument-transform#2]
Transformation does not work correct for relations. My "where" look like this:
`
   const prsima1where = {
       type: {
           name_contains: "some_name"
        }
    }
`
Util does not transform name_contains to the `name: { contains: "soma_name" }`. 
I have found that problem is in line https://github.com/prisma/binding-argument-transform/blob/29cc3942df4c180e222db6e12d9d673fee9d3e7d/src/whereConditions.ts#L38

**Comment by ryands17** [comment]
Solved by your PR :)
https://github.com/prisma/binding-argument-transform/pull/3
